name: secret-scan
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 6'  # Sat 06:00 UTC (≈09:00 BG)
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run secret scan
        run: bash scripts/secret-scan.sh .
